eureka:
  instance:
    hostname: ${EUREKA_URL:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: brasil
          uri: lb://BRASIL
          predicates:
            - Path=/brasil/**
        - id: japao
          uri: lb://JAPAO
          predicates:
            - Path=/japao/**

management:
  endpoints:
    web:
      exposure:
        include: "*"


